{% set version = "0.1.15" %}

package:
  name: thermofun
  version: {{ version }}

source:
  url: https://github.com/thermomod/thermofun/archive/v{{ version }}.tar.gz
  sha256: 5d9a586bce37e56d6f1d7a143ec3787e99e88ba3e21be6a0fb2538cadc5f58e4

build:
  number: 1
#  skip: True  # [py2k or osx or c_compiler == 'toolchain_c']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake>=3.13
    - ninja
  host:
    - boost
    - pybind11>=2.3.0
    - nlohmann_json>=3.6.1
    - numpy 1.14.*
    - python
  run:
    - boost
    - python
    - {{ pin_compatible('numpy') }}

about:
  home: https://thermohub.org/thermofun/thermofun/
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: Standalone library for calculating temperature and pressure corrections of thermodynamic data for substances and reactions.
  doc_url: https://thermohub.org/thermofun/thermofun/
  dev_url: https://github.com/thermomod/thermofun

extra:
  recipe-maintainers:
    - gdmiron
    - allanleal
